/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AncientRouteImport } from './routes/ancient'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as HaleriRouteImport } from './routes/haleri'
import { Route as MapRouteImport } from './routes/map'
import { Route as MysoreConflictsRouteImport } from './routes/mysore-conflicts'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as TimelineRouteImport } from './routes/timeline'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AncientRoute = AncientRouteImport.update({
  id: '/ancient',
  path: '/ancient',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const HaleriRoute = HaleriRouteImport.update({
  id: '/haleri',
  path: '/haleri',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const MysoreConflictsRoute = MysoreConflictsRouteImport.update({
  id: '/mysore-conflicts',
  path: '/mysore-conflicts',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ancient': typeof AncientRoute
  '/evidence': typeof EvidenceRoute
  '/glossary': typeof GlossaryRoute
  '/haleri': typeof HaleriRoute
  '/map': typeof MapRoute
  '/mysore-conflicts': typeof MysoreConflictsRoute
  '/sources': typeof SourcesRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ancient': typeof AncientRoute
  '/evidence': typeof EvidenceRoute
  '/glossary': typeof GlossaryRoute
  '/haleri': typeof HaleriRoute
  '/map': typeof MapRoute
  '/mysore-conflicts': typeof MysoreConflictsRoute
  '/sources': typeof SourcesRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ancient': typeof AncientRoute
  '/evidence': typeof EvidenceRoute
  '/glossary': typeof GlossaryRoute
  '/haleri': typeof HaleriRoute
  '/map': typeof MapRoute
  '/mysore-conflicts': typeof MysoreConflictsRoute
  '/sources': typeof SourcesRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ancient'
    | '/evidence'
    | '/glossary'
    | '/haleri'
    | '/map'
    | '/mysore-conflicts'
    | '/sources'
    | '/timeline'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ancient'
    | '/evidence'
    | '/glossary'
    | '/haleri'
    | '/map'
    | '/mysore-conflicts'
    | '/sources'
    | '/timeline'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ancient'
    | '/evidence'
    | '/glossary'
    | '/haleri'
    | '/map'
    | '/mysore-conflicts'
    | '/sources'
    | '/timeline'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AncientRoute: typeof AncientRoute
  EvidenceRoute: typeof EvidenceRoute
  GlossaryRoute: typeof GlossaryRoute
  HaleriRoute: typeof HaleriRoute
  MapRoute: typeof MapRoute
  MysoreConflictsRoute: typeof MysoreConflictsRoute
  SourcesRoute: typeof SourcesRoute
  TimelineRoute: typeof TimelineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ancient': {
      id: '/ancient'
      path: '/ancient'
      fullPath: '/ancient'
      preLoaderRoute: typeof AncientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/haleri': {
      id: '/haleri'
      path: '/haleri'
      fullPath: '/haleri'
      preLoaderRoute: typeof HaleriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mysore-conflicts': {
      id: '/mysore-conflicts'
      path: '/mysore-conflicts'
      fullPath: '/mysore-conflicts'
      preLoaderRoute: typeof MysoreConflictsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AncientRoute: AncientRoute,
  EvidenceRoute: EvidenceRoute,
  GlossaryRoute: GlossaryRoute,
  HaleriRoute: HaleriRoute,
  MapRoute: MapRoute,
  MysoreConflictsRoute: MysoreConflictsRoute,
  SourcesRoute: SourcesRoute,
  TimelineRoute: TimelineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
